apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

namespace: openshift-gitops

resources:
- labels-house-simpson.yaml
- labels-house-bouvier.yaml
- taint-house-bouvier.yaml
- taint-house-simpson.yaml
