apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: label-house-simpson
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.8
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/pull
              set -x
              echo ""
              echo "========================"
              echo "Applying labels to nodes..."

              oc label node compute-2 ingresscontroller=simpson
              oc label node compute-3 house=simpson
              
              echo "========================"
          imagePullPolicy: Always
          name: apply-labels
      serviceAccount: openshift-gitops-argocd-application-controller
      serviceAccountName: openshift-gitops-argocd-application-controller
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30