apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project001

bases:
- ../base

patchesStrategicMerge:
- storage-class-quota.yaml

resources:
- project001.yaml
- rolebind-to-user-user001.yaml
