apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project002
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster001/namespaces/project001
    repoURL: 'https://github.com/ralvares/gitops/'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true